### ISSUE TITLE
Install instructions in the README are incorrect

### ISSUE THREAD

**Issue by willsheppard** [httperf/httperf#43]
The README says:

```
    $ mkdir build
    $ cd build
    $ SRCDIR/configure
    $ make
    $ make install
```

But there is no script called `configure`.
There is a script called `configure.ac`, it says at the top to use autoconf... somehow.

Could the instructions please be updated so that someone with no experience can easily compile the program without having to look up how to use autoconf, etc.?

**Comment by MathynMovin** [comment]
Any update on this? I want to build the library but I don't know enough about autoconf to get it to build.

**Comment by gaimande** [comment]
Firstly, you have to run autoreconf to generate the **configure** file.
$ cd SRCDIR/
$ autoreconf -i

It may has an error about m4 directory. In that case, you have to create a m4 directory and run this command again.
$ mkdir -f SRCDIR/m4

**Comment by adonespitogo** [comment]
I was able to generate the `configure` file using `autoreconf -i`. But when I tried to execute the configure file using `./configure`, there is an error `Permission denied` even though I run it with `sudo ./configure`.

**Comment by holdenweb** [comment]
Very disappointed to see this issue unaddressed in two years. Please don't assume that everyone who comes to a project will be fully _au fait_ with trends in Unix development. I just wanted to do some performance testing and ended up in a minor yak-shave. If I have time I'll create a PR for the docs.

**Comment by holdenweb** [comment]
Now faced with `configure.ac:21: error: possibly undefined macro: AC_PROG_LIBTOOL` followed by a message that I should read the autoconf documentation. I don't think this is the tool I'm looking for.

**Comment by erikarn** [comment]
hi!

Sorry, life involved a new job, a new house, getting married and having a
baby. open source has to take a side break for a while. :-)



-a

**Comment by holdenweb** [comment]
That stuff will happen to you. I hope it's all enjoyable!

**Comment by jayesh-rao** [comment]
the following worked for me:
1. we need to generate the "configure" script 
libtoolize --force   (install libtool)
aclocal
autoheader
automake --force-missing --add-missing
autoconf
./configure

mkdir build; cd build
make
make install

**Comment by erikarn** [comment]
hm! lemme update the docs

**Comment by erikarn** [comment]
There, fixed README.md
